package com.example.dualingo_clone.database.info

const val url = "https://umtzxyrfsvufvihqziij.supabase.co"
const val key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdHp4eXJmc3Z1ZnZpaHF6aWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTE1MzA0ODQsImV4cCI6MjAyNzEwNjQ4NH0.HgzczBU5_iCGenOipm1MaXagSDKFnzmBQ_C4rOMEfwA"